import { customHelloBellaYzApo } from '@/app/fonts';
import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by Onlook'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en" className={`${customHelloBellaYzApo.variable}`} data-oid="uv:fyp0">
            <body className="" data-oid="2db-kjq">
                {children}
            </body>
        </html>;
}